catalog:
  process:
    - id: "process.format"
      label: "Format & wipe commands"
      value: "*format*"
      path: "process.deny_cmd_patterns"
    - id: "process.shutdown"
      label: "Shutdown & restart"
      value: "shutdown*"
      path: "process.deny_cmd_patterns"
    - id: "process.rmrf"
      label: "Recursive delete (rm -rf)"
      value: "rm -rf *"
      path: "process.deny_cmd_patterns"
    - id: "process.del"
      label: "Recursive delete (del /s)"
      value: "del /s *"
      path: "process.deny_cmd_patterns"
    - id: "process.powershell_remove"
      label: "PowerShell Remove-Item recurse"
      value: "powershell*Remove-Item* -Recurse"
      path: "process.deny_cmd_patterns"
  files:
    - id: "files.windows"
      label: "Windows directory"
      value: "C:\\Windows\\*"
      path: "files.deny_write_globs"
    - id: "files.program_files"
      label: "Program Files"
      value: "C:\\Program Files\\*"
      path: "files.deny_write_globs"
    - id: "files.program_files_x86"
      label: "Program Files (x86)"
      value: "C:\\Program Files (x86)\\*"
      path: "files.deny_write_globs"
    - id: "files.system32"
      label: "System32"
      value: "C:\\Windows\\System32"
      path: "files.deny_dirs"
    - id: "files.secrets"
      label: "Private keys (*.pem, *.key, id_rsa)"
      value: "*.pem"
      path: "files.deny_read_globs"
      extras:
        - "*.key"
        - "id_rsa"
  network:
    - id: "network.http"
      label: "Block plain HTTP"
      value: "^http://"
      path: "network.deny_url_regex"
    - id: "network.imds"
      label: "Instance metadata services"
      value: "169.254.*.*"
      path: "network.deny_hosts"
    - id: "network.imds_gcp"
      label: "GCP metadata"
      value: "metadata.google.internal"
      path: "network.deny_hosts"
  hotkeys:
    - id: "hotkeys.altf4"
      label: "ALT+F4"
      value: "ALT+F4"
      path: "hotkeys.deny"
    - id: "hotkeys.ctrlaltdelete"
      label: "CTRL+ALT+DELETE"
      value: "CTRL+ALT+DELETE"
      path: "hotkeys.deny"
    - id: "hotkeys.ctrlshiftesc"
      label: "CTRL+SHIFT+ESC"
      value: "CTRL+SHIFT+ESC"
      path: "hotkeys.deny"
  windows:
    - id: "windows.shelltray"
      label: "Windows Taskbar"
      value: "Shell_TrayWnd"
      path: "windows.deny_classes"
    - id: "windows.registry"
      label: "Registry Editor"
      value: "*Registry Editor*"
      path: "windows.deny_title_patterns"
    - id: "windows.gpo"
      label: "Local Group Policy Editor"
      value: "*Local Group Policy Editor*"
      path: "windows.deny_title_patterns"
  input:
    - id: "input.password"
      label: "Block 'password:' text"
      value: "(?i)password\\s*:"
      path: "input.deny_regex"
    - id: "input.secretkey"
      label: "Block 'secret key'"
      value: "(?i)secret\\s*key"
      path: "input.deny_regex"
